######################################################################
# Automatically generated by qmake (2.01a) Mon May 20 14:09:34 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myobject.h
SOURCES += myobject.cpp sample01.cpp
