######################################################################
# Automatically generated by qmake (2.01a) Mon May 20 15:29:31 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mymainwin.h myobject.h mywindow.h
SOURCES += mymainwin.cpp myobject.cpp mywindow.cpp top.cpp
