######################################################################
# Automatically generated by qmake (2.01a) ? 5? 25 10:26:08 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mymainwin.h myobject.h mywindow.h
SOURCES += ass3.cpp mymainwin.cpp myobject.cpp mywindow.cpp
