######################################################################
# Automatically generated by qmake (2.01a) ? 5? 25 16:47:42 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myobject.h
SOURCES += ass1.cpp myobject.cpp
