######################################################################
# Automatically generated by qmake (2.01a) Mon May 20 14:32:06 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myobject.h
SOURCES += ass1.cpp myobject.cpp
