######################################################################
# Automatically generated by qmake (2.01a) ? 5? 20 17:54:55 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mymainwin.h myobject.h mywindow.h
SOURCES += ass2.cpp mymainwin.cpp myobject.cpp mywindow.cpp
